name: test-cases-git-actions
on: [push,pull_request]
jobs:
  run-test-cases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          cd aca_backend_api
          pip install -r requirements.txt
      - name: Cleanup
        run: |
          bash clean.sh
      - name: Setup Containerization Advisor
        run: |
          bash setup.sh
      - name: Test with pytest
        run: |
          cd aca_backend_api
          python -m unittest discover -v -s test -p test_*.py
      - name: Test baselines
        run: |
          cd aca_entity_standardizer
          python events.py ${{toJSON(github.event)}}
          python benchmarks.py
          python run_tests.py
